
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_DATA_START = 'GET_DATA_START';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const SET_MONTH_DATA_START = 'SET_MONTH_DATA_START';
export const SET_MONTH_DATA_FAILED = 'SET_MONTH_DATA_FAILED';
export const SET_MONTH_DATA_SUCCESS = 'SET_MONTH_DATA_SUCCESS';
